// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreGame_WebAPI.Data;

#nullable disable

namespace StoreGame_WebAPI.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommandeJeu", b =>
                {
                    b.Property<int>("CommandesIdCommande")
                        .HasColumnType("int");

                    b.Property<int>("JeuxIdJeu")
                        .HasColumnType("int");

                    b.HasKey("CommandesIdCommande", "JeuxIdJeu");

                    b.HasIndex("JeuxIdJeu");

                    b.ToTable("CommandeJeu");
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.FavoriteGameStats", b =>
                {
                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdJeu")
                        .HasColumnType("int");

                    b.Property<double>("PercentInWishlists")
                        .HasColumnType("float");

                    b.Property<int>("TotalWishlists")
                        .HasColumnType("int");

                    b.ToTable("FavoriteGameStats");
                });

            modelBuilder.Entity("StoreGame_WebAPI.DTO.AverageReviewForEachGame", b =>
                {
                    b.Property<int>("IdJeu")
                        .HasColumnType("int");

                    b.Property<double>("MoyenneNote")
                        .HasColumnType("float");

                    b.ToTable("AverageReviewForEachGame");
                });

            modelBuilder.Entity("StoreGame_WebAPI.DTO.AverageScoreResult", b =>
                {
                    b.Property<double>("MoyenneNote")
                        .HasColumnType("float");

                    b.ToTable("AverageScoreResult");
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.GameReview", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdJeu")
                        .HasColumnType("int");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdReview");

                    b.HasIndex("IdJeu");

                    b.HasIndex("User", "IdJeu")
                        .IsUnique();

                    b.ToTable("GameReview");

                    b.HasData(
                        new
                        {
                            IdReview = 1,
                            Commentaire = "Ce jeu est incroyable! Les graphismes sont à couper le souffle, et l'histoire est passionnante. J'adore!",
                            IdJeu = 1,
                            Note = 4,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 2,
                            Commentaire = "J'ai passé des heures à jouer à ce jeu. C'est vraiment addictif, et les personnages sont attachants.",
                            IdJeu = 2,
                            Note = 3,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 3,
                            Commentaire = "Ce jeu mérite 5 étoiles. La jouabilité est fluide, et les niveaux sont bien conçus.",
                            IdJeu = 3,
                            Note = 5,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 4,
                            Commentaire = "The Witcher 3 est un chef-d'œuvre absolu! L'univers est riche, les quêtes sont captivantes. Ma note : 5/5.",
                            IdJeu = 4,
                            Note = 5,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 5,
                            Commentaire = "Rayman Legends est un jeu de plateforme incroyablement amusant. Les niveaux musicaux sont géniaux! Note : 4/5.",
                            IdJeu = 5,
                            Note = 4,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 6,
                            Commentaire = "Assassin's Creed Origins est un voyage passionnant dans l'Égypte antique. Les combats sont géniaux. Note : 4/5.",
                            IdJeu = 6,
                            Note = 4,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 7,
                            Commentaire = "Terraria est un jeu de construction addictif. L'exploration est infinie! Ma note : 4/5.",
                            IdJeu = 7,
                            Note = 4,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 8,
                            Commentaire = "Final Fantasy XIV est un MMORPG de qualité avec une histoire épique. Je recommande! Note : 5/5.",
                            IdJeu = 8,
                            Note = 5,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 9,
                            Commentaire = "Celeste est un jeu de plateforme exigeant mais gratifiant. Les défis sont stimulants. Note : 4/5.",
                            IdJeu = 9,
                            Note = 4,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 10,
                            Commentaire = "Red Dead Redemption 2 est une expérience immersive dans le Far West. Les détails sont incroyables. Note : 5/5.",
                            IdJeu = 10,
                            Note = 5,
                            User = "admin"
                        },
                        new
                        {
                            IdReview = 11,
                            Commentaire = "Les graphismes de ce jeu sont correct, et l'intrigue est palpitante. Je lui donne 3 étoiles!",
                            IdJeu = 1,
                            Note = 3,
                            User = "Grimworld"
                        },
                        new
                        {
                            IdReview = 12,
                            Commentaire = "J'ai été accro à ce jeu pendant des semaines. Les personnages sont super attachants, et l'aventure est passionnante. Ma note : 4/5.",
                            IdJeu = 2,
                            Note = 4,
                            User = "Grimworld"
                        },
                        new
                        {
                            IdReview = 13,
                            Commentaire = "Ce jeu mérite toutes les éloges. La jouabilité est fluide, et chaque niveau est un plaisir à parcourir. Ma note : 5/5.",
                            IdJeu = 3,
                            Note = 5,
                            User = "Grimworld"
                        },
                        new
                        {
                            IdReview = 14,
                            Commentaire = "Super Mario Odyssey est un jeu incroyable! Les graphismes sont époustouflants, et le gameplay est une pure joie. Ma note : 5/5.",
                            IdJeu = 1,
                            Note = 5,
                            User = "Tyzral"
                        },
                        new
                        {
                            IdReview = 15,
                            Commentaire = "J'ai passé d'innombrables heures à explorer chaque royaume de ce jeu. C'est un chef-d'œuvre du genre. Note : 5/5.",
                            IdJeu = 2,
                            Note = 5,
                            User = "Tyzral"
                        },
                        new
                        {
                            IdReview = 16,
                            Commentaire = "Ce jeu est tellement amusant! Les niveaux sont bien conçus, et les défis sont stimulants. Ma note : 3/5.",
                            IdJeu = 3,
                            Note = 3,
                            User = "Tyzral"
                        },
                        new
                        {
                            IdReview = 17,
                            Commentaire = "Ce jeu est décevant. Les graphismes sont médiocres, et l'histoire est ennuyeuse. Ma note : 2/5.",
                            IdJeu = 1,
                            Note = 2,
                            User = "THEFRIEND"
                        },
                        new
                        {
                            IdReview = 18,
                            Commentaire = "The Legend of Zelda: Breath of the Wild est un jeu surévalué. Je ne vois pas ce que les gens lui trouvent. Note : 2/5.",
                            IdJeu = 2,
                            Note = 2,
                            User = "THEFRIEND"
                        },
                        new
                        {
                            IdReview = 19,
                            Commentaire = "Minecraft est un jeu sans intérêt. Construire des choses n'a rien d'amusant. Ma note : 2/5.",
                            IdJeu = 3,
                            Note = 2,
                            User = "THEFRIEND"
                        });
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.JeuWishlist", b =>
                {
                    b.Property<int>("JeuxIdJeu")
                        .HasColumnType("int");

                    b.Property<int>("WishlistsId")
                        .HasColumnType("int");

                    b.HasKey("JeuxIdJeu", "WishlistsId");

                    b.HasIndex("WishlistsId");

                    b.ToTable("jeuWishlists");
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JeuIdJeu")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("JeuIdJeu");

                    b.HasIndex("User")
                        .IsUnique();

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idClient");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("AdresseCourriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressePhysique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdClient");

                    b.HasIndex("User");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            AdresseCourriel = "",
                            AdressePhysique = "",
                            Nom = "admin",
                            Prenom = "admin",
                            User = "admin"
                        },
                        new
                        {
                            IdClient = 2,
                            AdresseCourriel = "Tyzral@gmail.com",
                            AdressePhysique = "5150 rues des ormes",
                            Nom = "Beaudry",
                            Prenom = "Simon",
                            User = "Tyzral"
                        },
                        new
                        {
                            IdClient = 3,
                            AdresseCourriel = "Grimworld@gmail.com",
                            AdressePhysique = "221B Baker Street",
                            Nom = "Mercier",
                            Prenom = "Francis",
                            User = "Grimworld"
                        },
                        new
                        {
                            IdClient = 4,
                            AdresseCourriel = "ami@gmail.com",
                            AdressePhysique = "50 rue l'Amitié",
                            Nom = "Ami",
                            Prenom = "Ami",
                            User = "THEFRIEND"
                        },
                        new
                        {
                            IdClient = 7,
                            AdresseCourriel = "ami2@gmail.com",
                            AdressePhysique = "44 rue l'Amitié",
                            Nom = "Le",
                            Prenom = "Test1",
                            User = "Test1"
                        },
                        new
                        {
                            IdClient = 6,
                            AdresseCourriel = "ami3@gmail.com",
                            AdressePhysique = "45 rue l'Amitié",
                            Nom = "Le",
                            Prenom = "Test2",
                            User = "Test2"
                        });
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCommande");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommande"));

                    b.Property<bool>("Panier")
                        .HasColumnType("bit");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCommande");

                    b.HasIndex("User");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Compte", b =>
                {
                    b.Property<string>("User")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User");

                    b.ToTable("Compte");

                    b.HasData(
                        new
                        {
                            User = "admin",
                            Password = "123",
                            ProfileName = "Orignal"
                        },
                        new
                        {
                            User = "Tyzral",
                            Password = "123",
                            ProfileName = "Tyzral"
                        },
                        new
                        {
                            User = "Grimworld",
                            Password = "123",
                            ProfileName = "Grimworld"
                        },
                        new
                        {
                            User = "THEFRIEND",
                            Password = "123",
                            ProfileName = "ami"
                        },
                        new
                        {
                            User = "Test1",
                            Password = "123",
                            ProfileName = "LeTest1"
                        },
                        new
                        {
                            User = "Test2",
                            Password = "123",
                            ProfileName = "LeTest2"
                        });
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idGenre");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenre"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGenre");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            IdGenre = 1,
                            Name = "Action-aventure"
                        },
                        new
                        {
                            IdGenre = 2,
                            Name = "Plateforme"
                        },
                        new
                        {
                            IdGenre = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            IdGenre = 4,
                            Name = "Sandbox"
                        },
                        new
                        {
                            IdGenre = 5,
                            Name = "FPS"
                        },
                        new
                        {
                            IdGenre = 6,
                            Name = "Strategy"
                        },
                        new
                        {
                            IdGenre = 7,
                            Name = "Sports"
                        },
                        new
                        {
                            IdGenre = 8,
                            Name = "Simulation"
                        },
                        new
                        {
                            IdGenre = 9,
                            Name = "Puzzle"
                        },
                        new
                        {
                            IdGenre = 10,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Jeu", b =>
                {
                    b.Property<int>("IdJeu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idJeu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJeu"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdGenre")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomJeu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.HasKey("IdJeu");

                    b.HasIndex("IdGenre");

                    b.ToTable("Jeu");

                    b.HasData(
                        new
                        {
                            IdJeu = 1,
                            Description = "Aidez Mario à sauver la princesse Peach dans une aventure trépidante à travers de nombreux royaumes.",
                            IdGenre = 2,
                            ImagePath = "/image/SMOdyssey.png",
                            NomJeu = "Super Mario Odyssey",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 2,
                            Description = "Explorez le vaste monde d'Hyrule en incarnant le héros Link et affrontez de redoutables ennemis.",
                            IdGenre = 1,
                            ImagePath = "/image/LoZeldaBoTW.png",
                            NomJeu = "The Legend of Zelda: Breath of the Wild",
                            Prix = 79.989999999999995
                        },
                        new
                        {
                            IdJeu = 3,
                            Description = "Construisez et explorez un monde infini rempli de blocs, où seules vos limites sont votre créativité et votre imagination.",
                            IdGenre = 4,
                            ImagePath = "/image/Minecraft.png",
                            NomJeu = "Minecraft",
                            Prix = 29.989999999999998
                        },
                        new
                        {
                            IdJeu = 4,
                            Description = "Incarnez Geralt de Riv, un puissant chasseur de monstres, et embarquez dans une quête épique à travers un monde fantastique rempli de dangers et de choix moraux.",
                            IdGenre = 3,
                            ImagePath = "/image/TheWitcher3WildHunt.png",
                            NomJeu = "The Witcher 3: Wild Hunt",
                            Prix = 49.990000000000002
                        },
                        new
                        {
                            IdJeu = 5,
                            Description = "Rejoignez Rayman and ses amis dans des niveaux colorés et remplis de défis pour sauver le monde des créatures maléfiques.",
                            IdGenre = 2,
                            ImagePath = "/image/RaymanLegends.png",
                            NomJeu = "Rayman Legends",
                            Prix = 39.990000000000002
                        },
                        new
                        {
                            IdJeu = 6,
                            Description = "Découvrez l'histoire des origines de la confrérie des Assassins dans l'Égypte antique, et frayez-vous un chemin à travers des batailles épiques et des conspirations.",
                            IdGenre = 1,
                            ImagePath = "/image/ACOrigine.png",
                            NomJeu = "Assassin's Creed Origins",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 7,
                            Description = "Explorez, construisez et combattez dans un monde rempli de créatures mystérieuses et de trésors cachés.",
                            IdGenre = 4,
                            ImagePath = "/image/Terraria.png",
                            NomJeu = "Terraria",
                            Prix = 19.989999999999998
                        },
                        new
                        {
                            IdJeu = 8,
                            Description = "Plongez dans le monde de la saga légendaire Final Fantasy avec des milliers d'autres joueurs dans ce MMORPG riche en histoires et en combats épiques.",
                            IdGenre = 3,
                            ImagePath = "/image/FF14.png",
                            NomJeu = "Final Fantasy XIV",
                            Prix = 29.989999999999998
                        },
                        new
                        {
                            IdJeu = 9,
                            Description = "Aidez Madeline à surmonter ses peurs intérieures et à escalader la montagne de Celeste dans ce jeu de plateforme acclamé.",
                            IdGenre = 2,
                            ImagePath = "/image/Celeste.png",
                            NomJeu = "Celeste",
                            Prix = 19.989999999999998
                        },
                        new
                        {
                            IdJeu = 10,
                            Description = "Explorez le Far West américain à l'époque des hors-la-loi et participez à des braquages, des duels et des aventures épiques.",
                            IdGenre = 1,
                            ImagePath = "/image/RDR2.png",
                            NomJeu = "Red Dead Redemption 2",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 11,
                            Description = "Quittez la ville pour hériter de la vieille ferme de votre grand-père et transformez-la en un lieu prospère en cultivant des cultures, en élevant du bétail et en tissant des liens avec les habitants de la ville.",
                            IdGenre = 4,
                            ImagePath = "/image/stardewVal.png",
                            NomJeu = "Stardew Valley",
                            Prix = 14.99
                        },
                        new
                        {
                            IdJeu = 12,
                            Description = "Un vaste monde ouvert avec des quêtes épiques, des dragons redoutables et des mystères à découvrir.",
                            IdGenre = 3,
                            ImagePath = "/image/skyrim.png",
                            NomJeu = "The Elder Scrolls V: Skyrim",
                            Prix = 39.990000000000002
                        },
                        new
                        {
                            IdJeu = 13,
                            Description = "Incarnez Batman et combattez les super-vilains dans les rues sombres et corrompues d'Arkham City.",
                            IdGenre = 1,
                            ImagePath = "/image/batman.png",
                            NomJeu = "Batman: Arkham City",
                            Prix = 39.990000000000002
                        },
                        new
                        {
                            IdJeu = 14,
                            Description = "Plongez dans des donjons générés de manière procédurale, affrontez des monstres redoutables et obtenez des trésors légendaires dans ce jeu d'action-aventure inspiré de l'univers de Minecraft.",
                            IdGenre = 1,
                            ImagePath = "/image/minecraftDungeon.png",
                            NomJeu = "Minecraft: Dungeons",
                            Prix = 29.989999999999998
                        },
                        new
                        {
                            IdJeu = 15,
                            Description = "Gérez une colonie de survivants échoués sur une planète extraterrestre dans ce jeu de gestion de colonie complexe et captivant.",
                            IdGenre = 4,
                            ImagePath = "/image/rimworld.png",
                            NomJeu = "RimWorld",
                            Prix = 34.990000000000002
                        },
                        new
                        {
                            IdJeu = 16,
                            Description = "Revivez l'histoire épique de Cloud Strife et du groupe de résistants Avalanche dans ce remake du célèbre jeu de rôle japonais.",
                            IdGenre = 3,
                            ImagePath = "/image/ff7remake.png",
                            NomJeu = "Final Fantasy VII Remake",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 17,
                            Description = "Redécouvrez les aventures classiques de Crash Bandicoot dans une collection remasterisée comprenant les trois premiers jeux de la série.",
                            IdGenre = 2,
                            ImagePath = "/image/trilogy Crash.png",
                            NomJeu = "Crash Bandicoot N. Sane Trilogy",
                            Prix = 39.990000000000002
                        },
                        new
                        {
                            IdJeu = 18,
                            Description = "Explorez un univers de science-fiction dystopique, prenez des décisions morales difficiles et façonnez votre propre destinée dans ce RPG captivant.",
                            IdGenre = 3,
                            ImagePath = "/image/TOW.png",
                            NomJeu = "The Outer Worlds",
                            Prix = 49.990000000000002
                        },
                        new
                        {
                            IdJeu = 19,
                            Description = "Affrontez vos personnages préférés de Nintendo et d'autres franchises dans des combats épiques mettant en scène des crossovers incroyables.",
                            IdGenre = 1,
                            ImagePath = "/image/SSBrosUlti.png",
                            NomJeu = "Super Smash Bros. Ultimate",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 20,
                            Description = "Affrontez des ennemis redoutables en tant que 'Loup à un bras' dans ce jeu d'action-aventure intense et exigeant développé par FromSoftware.",
                            IdGenre = 1,
                            ImagePath = "/image/seikiro.png",
                            NomJeu = "Sekiro: Shadows Die Twice",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 21,
                            Description = "Plongez dans les profondeurs mystérieuses d'une planète océanique extraterrestre et survivez en explorant, en construisant et en découvrant les secrets de ce monde aquatique hostile.",
                            IdGenre = 4,
                            ImagePath = "/image/subnautica.png",
                            NomJeu = "Subnautica",
                            Prix = 29.989999999999998
                        },
                        new
                        {
                            IdJeu = 22,
                            Description = "Plongez dans un vaste monde de fantasy et menez une équipe de héros dans une quête pour sauver le monde de la destruction dans ce RPG isométrique riche en choix et en conséquences.",
                            IdGenre = 3,
                            ImagePath = "/image/DOS2.png",
                            NomJeu = "Divinity: Original Sin 2",
                            Prix = 44.990000000000002
                        },
                        new
                        {
                            IdJeu = 23,
                            Description = "Affrontez des hordes de démons infernaux dans ce jeu de tir frénétique et sanglant.",
                            IdGenre = 5,
                            ImagePath = "/image/DoomE.png",
                            NomJeu = "Doom Eternal",
                            Prix = 39.990000000000002
                        },
                        new
                        {
                            IdJeu = 24,
                            Description = "Revivez les batailles emblématiques de la Seconde Guerre mondiale dans ce jeu de tir à la première personne.",
                            IdGenre = 5,
                            ImagePath = "/image/BF5.png",
                            NomJeu = "Battlefield V",
                            Prix = 49.990000000000002
                        },
                        new
                        {
                            IdJeu = 25,
                            Description = "Prenez les commandes d'une équipe de football américain et menez-la vers la victoire ultime.",
                            IdGenre = 7,
                            ImagePath = "/image/Madden23.png",
                            NomJeu = "Madden NFL 23",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 26,
                            Description = "Plongez dans une histoire terrifiante et découvrez les sombres secrets qui vous entourent.",
                            IdGenre = 10,
                            ImagePath = "/image/Amnesia.png",
                            NomJeu = "Amnesia: Rebirth",
                            Prix = 29.989999999999998
                        },
                        new
                        {
                            IdJeu = 27,
                            Description = "Dominez le terrain de basket et vivez l'expérience de la NBA avec des joueurs célèbres.",
                            IdGenre = 7,
                            ImagePath = "/image/NBA2K23.png",
                            NomJeu = "NBA 2K23",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 28,
                            Description = "Prenez le contrôle d'une des factions fantastiques de l'univers de Warhammer et dominez le monde.",
                            IdGenre = 6,
                            ImagePath = "/image/TWW2.png",
                            NomJeu = "Total War: Warhammer II",
                            Prix = 49.990000000000002
                        },
                        new
                        {
                            IdJeu = 29,
                            Description = "Envolez-vous dans les cieux et explorez le monde entier avec des détails incroyablement réalistes.",
                            IdGenre = 8,
                            ImagePath = "/image/MFS.png",
                            NomJeu = "Microsoft Flight Simulator",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 30,
                            Description = "Vivez l'excitation du football avec des graphismes réalistes et une jouabilité améliorée.",
                            IdGenre = 7,
                            ImagePath = "/image/fifa23.png",
                            NomJeu = "FIFA 23",
                            Prix = 59.990000000000002
                        },
                        new
                        {
                            IdJeu = 31,
                            Description = "Créez et contrôlez des vies virtuelles dans ce jeu de simulation de vie réaliste.",
                            IdGenre = 8,
                            ImagePath = "/image/sims4.png",
                            NomJeu = "The Sims 4",
                            Prix = 39.990000000000002
                        },
                        new
                        {
                            IdJeu = 32,
                            Description = "Résolvez des énigmes et manipulez l'espace avec votre pistolet de portail dans ce jeu de puzzle captivant.",
                            IdGenre = 9,
                            ImagePath = "/image/P2.png",
                            NomJeu = "Portal 2",
                            Prix = 19.989999999999998
                        },
                        new
                        {
                            IdJeu = 33,
                            Description = "Plongez dans une guerre moderne avec des graphismes époustouflants et une expérience multijoueur intense.",
                            IdGenre = 5,
                            ImagePath = "/image/CODMW.png",
                            NomJeu = "Call of Duty: Modern Warfare",
                            Prix = 59.990000000000002
                        });
                });

            modelBuilder.Entity("CommandeJeu", b =>
                {
                    b.HasOne("StoreGame_WebAPI.entities.Commande", null)
                        .WithMany()
                        .HasForeignKey("CommandesIdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreGame_WebAPI.entities.Jeu", null)
                        .WithMany()
                        .HasForeignKey("JeuxIdJeu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.GameReview", b =>
                {
                    b.HasOne("StoreGame_WebAPI.entities.Jeu", "Jeu")
                        .WithMany()
                        .HasForeignKey("IdJeu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreGame_WebAPI.entities.Compte", "Compte")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("Jeu");
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.JeuWishlist", b =>
                {
                    b.HasOne("StoreGame_WebAPI.entities.Jeu", "Jeu")
                        .WithMany("JeuWishlists")
                        .HasForeignKey("JeuxIdJeu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreGame_WebAPI.Entities.Wishlist", "Wishlist")
                        .WithMany("JeuWishlists")
                        .HasForeignKey("WishlistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jeu");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.Wishlist", b =>
                {
                    b.HasOne("StoreGame_WebAPI.entities.Jeu", null)
                        .WithMany("Whislists")
                        .HasForeignKey("JeuIdJeu");

                    b.HasOne("StoreGame_WebAPI.entities.Compte", "Compte")
                        .WithOne("Wishlist")
                        .HasForeignKey("StoreGame_WebAPI.Entities.Wishlist", "User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Client", b =>
                {
                    b.HasOne("StoreGame_WebAPI.entities.Compte", "Compte")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Commande", b =>
                {
                    b.HasOne("StoreGame_WebAPI.entities.Compte", "Compte")
                        .WithMany("Commandes")
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Jeu", b =>
                {
                    b.HasOne("StoreGame_WebAPI.entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("StoreGame_WebAPI.Entities.Wishlist", b =>
                {
                    b.Navigation("JeuWishlists");
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Compte", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Wishlist")
                        .IsRequired();
                });

            modelBuilder.Entity("StoreGame_WebAPI.entities.Jeu", b =>
                {
                    b.Navigation("JeuWishlists");

                    b.Navigation("Whislists");
                });
#pragma warning restore 612, 618
        }
    }
}
